FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends default-jre-headless procps && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pyspark==3.5.3 pandas clickhouse-connect

WORKDIR /opt/spark-jobs

CMD ["tail", "-f", "/dev/null"]
